title: Teerasit Wongpa
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/teerasit-wongpa-9646b813b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-CLRL9HT8WP # your Google Analytics tracking ID here
