title: Teerasit Wongpa
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Nickname: Kiw
  <br><br>
  Age: <a id="age">unknown years</a> 
  <br><br>
  Location: NakhonPathom, Thailand
  <br><br>
  Language: Thai, English
  <br><br>
  <a href="https://www.linkedin.com/in/teerasit-wongpa-9646b813b/" class="fa links fa-linkedin"></a>
  <a href="https://github.com/Aicl0ud" class="fa links fa-github" aria-hidden="true"></a>
  <a href="mailto:teerasit.won@gmail.com" class="fa links fa-google"></a> 
  <a href="tel:+66925531998" class="fa links fa-phone"></a>
  
theme: jekyll-theme-minimal
google_analytics: G-CLRL9HT8WP # your Google Analytics tracking ID here
