title: Teerasit Wongpa
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Nickname: Kiw
  <br><br>
  Age: <a id="age">unknown years</a> 
  <br><br>
  Location: NakhonPathom, Thailand
  <br><br>
  <a href="https://www.linkedin.com/in/teerasit-wongpa-9646b813b/" class="fa fa-linkedin"></a>
  <a href="#" class="fa fa-github" aria-hidden="true"></a> 
  
theme: jekyll-theme-minimal
google_analytics: G-CLRL9HT8WP # your Google Analytics tracking ID here
